name: Test

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install modules
        run: npm ci
      - name: Test
        run: npm test
